"""empty message

Revision ID: 5405e408cb8e
Revises: 
Create Date: 2020-09-27 13:06:51.999788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5405e408cb8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummies')
    # ### end Alembic commands ###
